
version: 2

models:
  - name: fact_order_items
    description: "The fact table for order items"
    columns:
      - name: fact_key
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: session_id
      - name: song_id
      - name: song_key
      - name: user_key
      - name: artist_key
      - name: session_start_time
      - name: price
      - name: liked
      - name: liked_since

  - name: dim_users
    description: "The dimension table for users"
    columns:
      - name: user_key
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: user_id
      - name: user_lastname
      - name: user_name
      - name: user_since
      - name: country_code

  - name: dim_songs
    description: "The dimension table for songs"
    columns:
      - name: song_key
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: song_id
      - name: song_title
      - name: track_id
      - name: release
      - name: duration
      - name: year


  - name: dim_artists
    description: "The dimension table for artists"
    columns:
      - name: artist_key
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: artist_id
      - name: artist_name
      - name: artist_familiarity
      - name: artist_hotttnesss

  - name: dim_dates
    description: "The dimension table for dates"
    columns:
      - name: date_key
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: month
      - name: year
      - name: day_of_week

 